"""add likes table

Revision ID: 6f2f0b35a5c8
Revises: d820332dac81
Create Date: 2026-03-06 11:18:44.360737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2f0b35a5c8'
down_revision: Union[str, None] = 'd820332dac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_post_like', 'likes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_post_like', 'likes', type_='unique')
    # ### end Alembic commands ###
