"""add likes table and update relationships

Revision ID: ce51a8fb22e0
Revises: 6f2f0b35a5c8
Create Date: 2026-03-06 11:51:50.093593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce51a8fb22e0'
down_revision: Union[str, None] = '6f2f0b35a5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_post_comment', 'comments', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_post_comment', 'comments', type_='unique')
    # ### end Alembic commands ###
